### ISSUE TITLE
Recommended issue link uses non-existent labels

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustc-dev-guide#2650]
The dev guide links to [this](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Arust-lang+no%3Aassignee+label%3AE-easy%2C%22good+first+issue%22%2Cgood-first-issue%2CE-medium%2CEasy%2CE-help-wanted%2CE-mentor+-label%3AS-blocked+-linked%3Apr+) for finding issues to work on, but that page shows some github warnings:

<img width="405" height="122" alt="Image" src="https://github.com/user-attachments/assets/2e726b17-7a93-4ab8-a29b-c7e5cf8b1270" />

**Comment by RalfJung** [comment]
Oddly, however, there are issues with label "good first issue":

<img width="778" height="82" alt="Image" src="https://github.com/user-attachments/assets/56aa0780-0c7f-43e5-be09-6496bb5f803d" />

Not sure why github is showing this warning.

**Comment by reddevilmidzy** [comment]
My warning is slightly different

<img width="1758" height="363" alt="Image" src="https://github.com/user-attachments/assets/0ac30ec3-5ef1-40e3-8b51-e8af68a8ce82" />

It seems to be a GitHub issue, what do you think about changing it to a different link?

changed `/issues?` to `/search?`

https://github.com/search?q=is%3Aopen+is%3Aissue+org%3Arust-lang+no%3Aassignee+label%3AE-easy%2C%22good+first+issue%22%2Cgood-first-issue%2CE-medium%2CEasy%2CE-help-wanted%2CE-mentor+-label%3AS-blocked+-linked%3Apr+&type=issues&utf8=%E2%9C%93&p=1

The result is the same, but there is no warning.

**Comment by BoxyUwU** [comment]
Fixed by #2679 I think?

**Comment by reddevilmidzy** [comment]
<img width="2452" height="638" alt="Image" src="https://github.com/user-attachments/assets/0638a22b-e4b1-4cb3-80dd-934d0808b49b" />

I still get a warning that rust-lang org is not valid. Maybe this only happens to people who aren't rust-lang members?

**Comment by BoxyUwU** [comment]
Hmm I'll re-open this then though i'm not sure what there is to do about that 🤔

**Comment by RalfJung** [comment]
Very odd that the filter seems to work (it actually does filter by org, judging from the screenshot) but also shows a warning.

**Comment by jyn514** [comment]
github seems to have fixed this on their end. i don't think there's any point in tracking github's own bug here.

<img width="1064" height="734" alt="Image" src="https://github.com/user-attachments/assets/b96d2838-8fa7-4a3e-a561-8f4fa029adc9" />
