### ISSUE TITLE
Add more info about stages

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-dev-guide#726]
Some very helpful discussion here: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/why.20stage.202.3F

**Comment by jyn514** [comment]
@mark-i-m do you think this was addressed by #857? Or is there more info that should be added?

**Comment by mark-i-m** [comment]
I changed the title. I think the current docs still don't get me to the point where I fully/intuitively understand the requirements for bootstrapping. For example. I still find it hard to grasp the answers to things like this:

- Why is stage 2 needed at all? (which Mark answers in that thread)
- Why can't we make rustc build with beta std or vice versa?
- Why is cfg(bootsrap) needed?
- Why not in the compiler?
- Why build the compiler with beta instead of something else?
- etc

I believe you have had a deep dive into these sorts of questions recently too.

**Comment by jyn514** [comment]
> Why can't we make rustc build with beta std or vice versa?

This is a policy decision (that I don't agree with, but has merits). See https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Building.20rustc.20with.20beta.20libstd for a _very_ long discussion, I'll try to get around to summarizing it at some point.

> Why is cfg(bootsrap) needed?

Does this help? https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#complications-of-bootstrapping

> Why not in the compiler? 

Does this help? https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#why-does-only-libstd-use-cfgbootstrap

> Why build the compiler with beta instead of something else?

I've been meaning to ask that myself ... I think it's come up on zulip a few times, I need to go back and look.

**Comment by Mark-Simulacrum** [comment]
> Why build the compiler with beta instead of something else?
> > I've been meaning to ask that myself ... I think it's come up on zulip a few times, I need to go back and look.

Distributions (at least) want to be able to build the next Rust, say, 1.46.0 with 1.45.0. This means bootstrapping with beta in our CI (which will become bootstrapping with stable on beta branch, bootstrapping with previous stable on stable branch).

We also have the often overlooked, and somewhat softer, requirement that Rust 1.46.0 should be able to build 1.46.0; this is sort of covered by a stage 1/2 build but often runs into trouble with bootstrap tools using unstable features, though we've been gradually moving away from that over time. rustbuild does automatically detect this situation and skips passing --cfg bootstrap when building the compiler & std, though.

---

Just wanted to note that as always I am happy to chat about these things, let me know.
